#ifndef __PROCALC_FRAGMENTS_F_RAYCAST_COMPONENT_KINDS_HPP__
#define __PROCALC_FRAGMENTS_F_RAYCAST_COMPONENT_KINDS_HPP__


enum class ComponentKind {
  C_BEHAVIOUR,
  C_SPATIAL,
  C_RENDER,
  C_RENDER_SPATIAL
};


#endif
