#ifndef __PROCALC_STATE_IDS_HPP__
#define __PROCALC_STATE_IDS_HPP__


enum {
  ST_NORMAL_CALCULATOR_0,
  ST_NORMAL_CALCULATOR_1,
  ST_NORMAL_CALCULATOR_2,
  ST_NORMAL_CALCULATOR_3,
  ST_NORMAL_CALCULATOR_4,
  ST_NORMAL_CALCULATOR_5,
  ST_NORMAL_CALCULATOR_6,
  ST_NORMAL_CALCULATOR_7,
  ST_NORMAL_CALCULATOR_8,
  ST_NORMAL_CALCULATOR_9,
  ST_DANGER_INFINITY,
  ST_SHUFFLED_KEYS,
  ST_ARE_YOU_SURE,
  ST_ITS_RAINING_TETROMINOS,
  ST_OFFICE_ASSISTANT,
  ST_YOUVE_GOT_MAIL,
  ST_SUICIDE_MISSION,
  ST_LIMBO,
  ST_A_SIMPLE_FAVOUR,
  ST_CLIPPYS_REVENGE,
  ST_T_MINUS_2_MINUTES,
  ST_BACK_TO_NORMAL,

  // TODO: Remove
  ST_RAYCAST
};


#endif
