#ifndef __PROCALC_STATE_IDS_HPP__
#define __PROCALC_STATE_IDS_HPP__


enum {
  ST_NORMAL_CALCULATOR_0,     // 2018
  ST_NORMAL_CALCULATOR_1,
  ST_NORMAL_CALCULATOR_2,
  ST_NORMAL_CALCULATOR_3,
  ST_NORMAL_CALCULATOR_4,
  ST_NORMAL_CALCULATOR_5,
  ST_NORMAL_CALCULATOR_6,
  ST_NORMAL_CALCULATOR_7,
  ST_NORMAL_CALCULATOR_8,
  ST_NORMAL_CALCULATOR_9,
  ST_DANGER_INFINITY,
  ST_SHUFFLED_KEYS,           // 1992
  ST_ARE_YOU_SURE,            // 1993
  ST_ITS_RAINING_TETROMINOS,  // 1994
  ST_MAKING_PROGRESS,         // 1995
  ST_YOUVE_GOT_MAIL,          // 1996
  ST_GOING_IN_CIRCLES,        // 1997
  ST_DOOMSWEEPER,             // 1998
  ST_T_MINUS_TWO_MINUTES,     // 1999
  ST_BACK_TO_NORMAL,          // 2018

  ST_TEST
};


#endif
