#ifndef __PROCALC_STATE_IDS_HPP__
#define __PROCALC_STATE_IDS_HPP__


enum {
  ST_NORMAL_CALCULATOR_0,
  ST_NORMAL_CALCULATOR_1,
  ST_NORMAL_CALCULATOR_2,
  ST_NORMAL_CALCULATOR_3,
  ST_NORMAL_CALCULATOR_4,
  ST_NORMAL_CALCULATOR_5,
  ST_NORMAL_CALCULATOR_6,
  ST_NORMAL_CALCULATOR_7,
  ST_NORMAL_CALCULATOR_8,
  ST_NORMAL_CALCULATOR_9,
  ST_DANGER_INFINITY,
  ST_SHUFFLED_KEYS,
  ST_LOGIN_SCREEN,
  ST_RAYCAST
};


#endif
