include(ExternalProject)

set(GOOGLE_TEST_CMAKE_ARGS
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
)

ExternalProject_Add(googleTest
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/srcs/googleTest

  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG release-1.8.0

  CMAKE_ARGS ${GOOGLE_TEST_CMAKE_ARGS}
)
