include(ExternalProject)

set(TINYXML2_CMAKE_ARGS
  -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
  -DCMAKE_INSTALL_PREFIX:PATH=<INSTALL_DIR>
  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
  -DCMAKE_OSX_ARCHITECTURES=${CMAKE_OSX_ARCHITECTURES}
)

ExternalProject_Add(libTinyXml2
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/srcs/tinyxml2

  GIT_REPOSITORY https://github.com/leethomason/tinyxml2.git
  GIT_TAG 6.0.0

  INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/tinyxml2
  CMAKE_ARGS ${TINYXML2_CMAKE_ARGS}
)
